//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="User.SimulatedDifferentialDrive.2006.M06, Version=0.0.0.0, Culture=neutral, Publi" +
    "cKeyToken=0d3af891cb183898")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace ECEC356_Final_Project.Proxy {
    
    
    /// <summary>
    ///            ECEC356_Final_Project state
    ///            </summary>
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
        "roject.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
        "roject.html", ElementName="ECEC356_Final_ProjectState")]
    [global::System.ComponentModel.DescriptionAttribute("ECEC356_Final_Project state")]
    public class ECEC356_Final_ProjectState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ECEC356_Final_ProjectState() {
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState _SpeechRecognizerState;
        
        /// <summary>
        ///            The speech recognizer's state
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("The speech recognizer\'s state.")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState SpeechRecognizerState {
            get {
                return this._SpeechRecognizerState;
            }
            set {
                this._SpeechRecognizerState = value;
            }
        }
        
        private global::System.Collections.Generic.List<global::ECEC356_Final_Project.Proxy.EventListEntry> _SpeechEvents;
        
        /// <summary>
        ///            Past speech events received from speech recognizer
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Past speech events received from speech recognizer.")]
        public global::System.Collections.Generic.List<global::ECEC356_Final_Project.Proxy.EventListEntry> SpeechEvents {
            get {
                return this._SpeechEvents;
            }
            set {
                this._SpeechEvents = value;
            }
        }
        
        private double _Angle;
        
        /// <summary>
        ///            Angle
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Angle")]
        public double Angle {
            get {
                return this._Angle;
            }
            set {
                this._Angle = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ECEC356_Final_ProjectState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::ECEC356_Final_Project.Proxy.ECEC356_Final_ProjectState typedTarget = ((global::ECEC356_Final_Project.Proxy.ECEC356_Final_ProjectState)(target));
            if ((this._SpeechRecognizerState != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState tmp = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState();
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechRecognizerState)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                typedTarget._SpeechRecognizerState = tmp;
            }
            if ((this._SpeechEvents != null)) {
                int count = this._SpeechEvents.Count;
                global::System.Collections.Generic.List<global::ECEC356_Final_Project.Proxy.EventListEntry> tmp0 = new global::System.Collections.Generic.List<global::ECEC356_Final_Project.Proxy.EventListEntry>(count);
                for (int index = 0; (index < count); index = (index + 1)) {
                    global::ECEC356_Final_Project.Proxy.EventListEntry tmp1 = default(global::ECEC356_Final_Project.Proxy.EventListEntry);
                    if ((this._SpeechEvents[index] != null)) {
                        global::ECEC356_Final_Project.Proxy.EventListEntry tmp2 = new global::ECEC356_Final_Project.Proxy.EventListEntry();
                        ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechEvents[index])).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                        tmp1 = tmp2;
                    }
                    tmp0.Add(tmp1);
                }
                typedTarget._SpeechEvents = tmp0;
            }
            typedTarget._Angle = this._Angle;
        }
        
        /// <summary>
        ///Clones ECEC356_Final_ProjectState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::ECEC356_Final_Project.Proxy.ECEC356_Final_ProjectState target0 = new global::ECEC356_Final_Project.Proxy.ECEC356_Final_ProjectState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ECEC356_Final_ProjectState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._SpeechRecognizerState == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechRecognizerState)).Serialize(writer);
            }
            if ((this._SpeechEvents == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._SpeechEvents.Count);
                for (int indexSpeechEvents = 0; (indexSpeechEvents < this._SpeechEvents.Count); indexSpeechEvents = (indexSpeechEvents + 1)) {
                    if ((this._SpeechEvents[indexSpeechEvents] == null)) {
                        writer.Write(((byte)(0)));
                    }
                    else {
                        writer.Write(((byte)(1)));
                        ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechEvents[indexSpeechEvents])).Serialize(writer);
                    }
                }
            }
            writer.Write(this._Angle);
        }
        
        /// <summary>
        ///Deserializes ECEC356_Final_ProjectState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ECEC356_Final_ProjectState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                this._SpeechRecognizerState = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizerState())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                int count0 = reader.ReadInt32();
                this._SpeechEvents = new global::System.Collections.Generic.List<global::ECEC356_Final_Project.Proxy.EventListEntry>(count0);
                for (int index0 = 0; (index0 < count0); index0 = (index0 + 1)) {
                    this._SpeechEvents.Add(default(global::ECEC356_Final_Project.Proxy.EventListEntry));
                    if ((reader.ReadByte() != 0)) {
                        this._SpeechEvents[index0] = ((global::ECEC356_Final_Project.Proxy.EventListEntry)(((Microsoft.Dss.Core.IDssSerializable)(new global::ECEC356_Final_Project.Proxy.EventListEntry())).Deserialize(reader)));
                    }
                }
            }
            this._Angle = reader.ReadDouble();
            return this;
        }
    }
    
    /// <summary>
    ///            EventListEntry - A list of events that have occurred
    ///            </summary>
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
        "roject.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
        "roject.html", ElementName="EventListEntry")]
    [global::System.ComponentModel.DescriptionAttribute("EventListEntry - A list of events that have occurred")]
    public class EventListEntry : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public EventListEntry() {
        }
        
        private long _Timestamp;
        
        /// <summary>
        ///            Timestamp when the event occurred
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Timestamp when the event occurred")]
        public long Timestamp {
            get {
                return this._Timestamp;
            }
            set {
                this._Timestamp = value;
            }
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification _SpeechDetected;
        
        /// <summary>
        ///            Speech Detected Notification
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Speech Detected Notification")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification SpeechDetected {
            get {
                return this._SpeechDetected;
            }
            set {
                this._SpeechDetected = value;
            }
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification _SpeechRecognized;
        
        /// <summary>
        ///            Speech Recognized Notification
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Speech Recognized Notification")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification SpeechRecognized {
            get {
                return this._SpeechRecognized;
            }
            set {
                this._SpeechRecognized = value;
            }
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification _RecognitionRejected;
        
        /// <summary>
        ///            Speech Rejected Notification
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Speech Rejected Notification")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification RecognitionRejected {
            get {
                return this._RecognitionRejected;
            }
            set {
                this._RecognitionRejected = value;
            }
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification _BeamDirectionChanged;
        
        /// <summary>
        ///            Speech Detected Notification
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Speech Detected Notification")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification BeamDirectionChanged {
            get {
                return this._BeamDirectionChanged;
            }
            set {
                this._BeamDirectionChanged = value;
            }
        }
        
        private global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation _SpeechInformation;
        
        /// <summary>
        ///            Speech Information
        ///            </summary>
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Speech Information")]
        public global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation SpeechInformation {
            get {
                return this._SpeechInformation;
            }
            set {
                this._SpeechInformation = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current EventListEntry to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::ECEC356_Final_Project.Proxy.EventListEntry typedTarget = ((global::ECEC356_Final_Project.Proxy.EventListEntry)(target));
            typedTarget._Timestamp = this._Timestamp;
            if ((this._SpeechDetected != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification tmp = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechDetected)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                typedTarget._SpeechDetected = tmp;
            }
            if ((this._SpeechRecognized != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification tmp0 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechRecognized)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                typedTarget._SpeechRecognized = tmp0;
            }
            if ((this._RecognitionRejected != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification tmp1 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(this._RecognitionRejected)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp1)));
                typedTarget._RecognitionRejected = tmp1;
            }
            if ((this._BeamDirectionChanged != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification tmp2 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification();
                ((Microsoft.Dss.Core.IDssSerializable)(this._BeamDirectionChanged)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                typedTarget._BeamDirectionChanged = tmp2;
            }
            if ((this._SpeechInformation != null)) {
                global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation tmp3 = new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation();
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechInformation)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp3)));
                typedTarget._SpeechInformation = tmp3;
            }
        }
        
        /// <summary>
        ///Clones EventListEntry
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::ECEC356_Final_Project.Proxy.EventListEntry target0 = new global::ECEC356_Final_Project.Proxy.EventListEntry();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current EventListEntry to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Timestamp);
            if ((this._SpeechDetected == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechDetected)).Serialize(writer);
            }
            if ((this._SpeechRecognized == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechRecognized)).Serialize(writer);
            }
            if ((this._RecognitionRejected == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._RecognitionRejected)).Serialize(writer);
            }
            if ((this._BeamDirectionChanged == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._BeamDirectionChanged)).Serialize(writer);
            }
            if ((this._SpeechInformation == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._SpeechInformation)).Serialize(writer);
            }
        }
        
        /// <summary>
        ///Deserializes EventListEntry
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized EventListEntry</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Timestamp = reader.ReadInt64();
            if ((reader.ReadByte() != 0)) {
                this._SpeechDetected = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechDetectedNotification())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._SpeechRecognized = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognizedNotification())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._RecognitionRejected = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechRecognitionRejectedNotification())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._BeamDirectionChanged = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.BeamDirectionChangedNotification())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._SpeechInformation = ((global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation)(((Microsoft.Dss.Core.IDssSerializable)(new global::Microsoft.Robotics.Services.Sensors.Kinect.MicArraySpeechRecognizer.Proxy.SpeechInformation())).Deserialize(reader)));
            }
            return this;
        }
    }
    
    /// <summary>
    ///            Provides access to a simulated differential drive service.\n(Uses the Generic Differential Drive contract.
    ///            </summary>
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DescriptionAttribute("Provides access to a simulated differential drive service.\\n(Uses the Generic Dif" +
        "ferential Drive contract.")]
    [global::System.ComponentModel.DisplayNameAttribute("(User) Simulated Generic Differential Drive")]
    public class Contract {
        
        public const string Identifier = "http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
            "roject.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
                    "roject.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
                    "roject.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.DriveOperations = new global::Microsoft.Robotics.Services.Drive.Proxy.DriveOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.DriveOperations, "http://schemas.microsoft.com/robotics/simulation/services/2006/05/ecec356_final_p" +
                        "roject.html", "DriveOperations", ""));
        }
        
        public global::Microsoft.Robotics.Services.Drive.Proxy.DriveOperations DriveOperations;
    }
}
